os: linux
dist: bionic
language: python

addons:
  apt:
    update: true

env:
  global:
    - secure: "VJSdyR3BUpDGf7ot0I+GvSVR77TaMgxgscW1pFgxeitr3XvZ9la+PMuSqKH1B1TR/8Gq+l507FnQb1I/zjzUOvomX2gnsL6CcbTml8DKUz12kmQ0ixGT5IxZjDuBDvJwOJlRg1JLgJkcxMHa9EEmDZTh7Feyu7jJC9qeGKSyjFw="
  jobs:
    - BCBIO_DOCKER_PRIVILEGED=True ARVADOS_API_HOST=qr1hi.arvadosapi.com

before_install:
  # Fix issue with boto2 and gce https://github.com/travis-ci/travis-ci/issues/7940#issuecomment-311046316
  - export BOTO_CONFIG=/dev/null
  # Temporal fix for networking problem: https://github.com/travis-ci/travis-ci/issues/1484
  - echo "127.0.1.1 "`hostname` | sudo tee /etc/hosts

install:
  - date
  - python ./scripts/bcbio_nextgen_install.py ${HOME}/local/share/bcbio --tooldir=${HOME}/local --nodata
  - date
  - export PATH=${HOME}/local/share/bcbio/anaconda/bin:${HOME}/local/bin:${PATH}
  - bcbio_nextgen.py upgrade --tooldir=${HOME}/local
  - date
  # Update to latest bcbio-nextgen code
  - rm -rf ${HOME}/local/share/bcbio/anaconda/lib/python*/site-packages/bcbio
  - rm -rf ${HOME}/local/share/bcbio/anaconda/lib/python*/site-packages/bcbio_nextgen-*
  - python setup.py install

script:
  - pytest -v tests/unit
  - pytest -v tests/integration

after_failure:
  - df -h

notifications:
  email: false
  slack:
    secure: iMn3Iih7cVmWci7A/Rpozc9Fn5IDKr3o6Y7XAWHEBiOEFlBwkC3oHFZxTC1+wZQiDNR87yVF9z3+FhYTYizpUeCPMddfNLMzdcO0EGtpckZOzX7aaFjqQCWhtucDnDQYaHhZIPKATrWvpPSYm7bpyp/p9cqgE/a9uvFLRMrIyzM=
