os: linux
dist: bionic
language: python

addons:
  apt:
    update: true

before_install:
  # Fix issue with boto2 and gce https://github.com/travis-ci/travis-ci/issues/7940#issuecomment-311046316
  - export BOTO_CONFIG=/dev/null
  # Temporal fix for networking problem: https://github.com/travis-ci/travis-ci/issues/1484
  - echo "127.0.1.1 "`hostname` | sudo tee /etc/hosts

install:
  - date
  - python ./scripts/bcbio_nextgen_install.py ${HOME}/local/share/bcbio --tooldir=${HOME}/local --nodata
  - date
  - export PATH=${HOME}/local/share/bcbio/anaconda/bin:${HOME}/local/bin:${PATH}
  # Update to latest bcbio-nextgen code
  - rm -rf ${HOME}/local/share/bcbio/anaconda/lib/python*/site-packages/bcbio
  - rm -rf ${HOME}/local/share/bcbio/anaconda/lib/python*/site-packages/bcbio_nextgen-*
  - python setup.py install

jobs:
  include:
    - script: pytest -v -m install_required tests
      name: "Tests requiring bcbio install"
    - script: pytest -v -m "not install_required" tests
      name: "Tests not requiring bcbio install"

after_failure:
  - df -h

notifications:
  email: false
  slack:
    secure: iMn3Iih7cVmWci7A/Rpozc9Fn5IDKr3o6Y7XAWHEBiOEFlBwkC3oHFZxTC1+wZQiDNR87yVF9z3+FhYTYizpUeCPMddfNLMzdcO0EGtpckZOzX7aaFjqQCWhtucDnDQYaHhZIPKATrWvpPSYm7bpyp/p9cqgE/a9uvFLRMrIyzM=
